# Generated by Django 2.2.4 on 2020-02-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_name',
            new_name='companyname',
        ),
    ]
