# Generated by Django 2.2.4 on 2020-02-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0002_auto_20200201_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
    ]
