# Generated by Django 2.2.4 on 2020-02-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0004_json'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Json',
            new_name='Jsonf',
        ),
    ]
