# Generated by Django 2.2.4 on 2020-02-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0005_auto_20200201_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonf',
            old_name='data',
            new_name='jdata',
        ),
    ]
