# Generated by Django 2.2.4 on 2020-02-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0006_auto_20200201_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
