# Generated by Django 2.2.4 on 2020-02-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0007_companies_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('companyname', 'cik', 'primarysymbol')},
        ),
    ]
