# Generated by Django 2.2.4 on 2020-02-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0008_auto_20200201_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
