# Generated by Django 2.2.4 on 2020-02-02 06:49

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0011_remove_companies_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatafileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='pd_dataframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EaganJones.DatafileModel'),
        ),
    ]
