# Generated by Django 2.2.4 on 2020-02-02 12:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0014_auto_20200202_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='json_data',
        ),
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', jsonfield.fields.JSONField(default=dict)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EaganJones.Companies')),
            ],
        ),
    ]
