# Generated by Django 2.2.4 on 2020-02-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0016_auto_20200202_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='json_file',
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EaganJones.Companies'),
        ),
    ]
