# Generated by Django 2.2.4 on 2020-02-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0017_auto_20200202_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonfile',
            name='name',
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EaganJones.JsonFile'),
        ),
    ]
