# Generated by Django 2.2.4 on 2020-02-02 16:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0018_auto_20200202_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='name',
        ),
        migrations.AddField(
            model_name='companies',
            name='jsonnn',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JsonFile',
        ),
    ]
