# Generated by Django 3.0.2 on 2020-01-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200112_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
