# Generated by Django 3.0.2 on 2020-03-17 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec1', models.CharField(blank=True, max_length=750)),
                ('rec2', models.CharField(blank=True, max_length=750)),
                ('rec3', models.CharField(blank=True, max_length=750)),
                ('rec4', models.CharField(blank=True, max_length=750)),
                ('rec5', models.CharField(blank=True, max_length=750)),
                ('rec6', models.CharField(blank=True, max_length=750)),
                ('rec7', models.CharField(blank=True, max_length=750)),
                ('rec8', models.CharField(blank=True, max_length=750)),
                ('rec9', models.CharField(blank=True, max_length=750)),
                ('rec10', models.CharField(blank=True, max_length=750)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
