# Generated by Django 3.0.2 on 2020-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='product_id',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
