# Generated by Django 3.0.2 on 2020-03-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200317_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
