# Generated by Django 3.0.2 on 2020-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200318_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['pro_id']},
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='product_id',
            new_name='pro_id',
        ),
    ]
