# Generated by Django 3.0.2 on 2020-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200318_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['product_id']},
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='pro_id',
            new_name='product_id',
        ),
    ]
