# Generated by Django 3.0.2 on 2020-03-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200318_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['product']},
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='product_id',
            new_name='product',
        ),
    ]
