# Generated by Django 3.0.2 on 2020-03-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200319_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderpmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useri', models.CharField(blank=True, max_length=750, null=True)),
                ('orderi', models.CharField(blank=True, max_length=750, null=True)),
                ('producti', models.CharField(blank=True, max_length=750, null=True)),
                ('product_name', models.CharField(blank=True, max_length=750, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categotyi', models.CharField(blank=True, max_length=750, null=True)),
                ('category_name', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
    ]
