# Generated by Django 3.0.2 on 2020-03-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_orderpmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpmp',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
