# Generated by Django 3.0.2 on 2020-03-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200320_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderpmp',
        ),
    ]
