# Generated by Django 2.2.4 on 2020-01-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
