# Generated by Django 2.2.4 on 2020-01-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
    ]
