# Generated by Django 3.0.2 on 2020-03-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderpmp_total_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpmp',
            name='parent_cat',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
